-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

hl.config({
    autogenerated = false
})

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Default
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Include specific monitor configs in local.lua

---------------------
---- MY PROGRAMS ----
---------------------

require("programs")

-------------------
---- AUTOSTART ----
-------------------

require("autostart")

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

require("environment")

---------------------------
-- Host-specific configs --
---------------------------

-- Set configs specific to a certain machine, like monitor configs, that differ from the default.
--
-- Create an empty "local.lua" file if no specific configs are needed.
require("local")

-----------------------
----- PERMISSIONS -----
-----------------------

-- TODO

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-----------------------
---- LOOK AND FEEL ----
-----------------------

require("looks")
require("behavior")

----------------
---- LAYOUT ----
----------------

require("layout")

---------------
---- INPUT ----
---------------

require("input")

------------------
---- KEYBINDS ----
------------------

require("keybinds")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

require("rules")
