-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- TODO: separate into different file

-- Default (random monitor)
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Laptop monitor
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1.25,
})

-- Second monitor
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100",
    position = "auto-right",
    scale = 1,
})

-- Work monitor
hl.monitor({
    output = "DP-1",
    mode = "preferred",
    position = "0x0",
    scale = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal             = "alacritty"
local terminalAlt          = "ghostty --gtk-single-instance=true"
local fileManager          = "nautilus"
local menu                 = "killall rofi || rofi -show drun -icon-theme breeze-dark"
local windowSwitcher       = "killall rofi || rofi -show window -icon-theme breeze-dark"
local browser              = "firefox"
local browser2             = "chromium --disable-features=WaylandWpColorManagerV1"
local clipboardManager     = "killall rofi || cliphist list | rofi -dmenu | cliphist decode | wl-copy"
local passwordManager      = "bitwarden-desktop"
local messagingPlatform    = "gio launch ~/.local/share/applications/teams-pwa"
local messagingPlatformAlt = "gio launch ~/.local/share/applications/odoo-pwa"
local powerMenu            = "killall rofi; bash ~/.config/waybar/scripts/power-menu/powermenu.sh"
local bluetoothMenu        = "killall rofi; bash ~/.config/waybar/scripts/rofi-bluetooth"
local wifiMenu             = "killall rofi; bash ~/.config/waybar/scripts/rofi-wifi-menu.sh"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")

    hl.exec_cmd("swaync &")

    hl.exec_cmd("~/.config/hypr/scripts/waybar-dynamic-config.sh")
    hl.exec_cmd("waybar 2>/tmp/stderr >/tmp/stdout &")

    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("hypridle &")

    hl.exec_cmd("~/.config/hypr/scripts/eww-open-all.sh &")

    hl.exec_cmd("XDG_MENU_PREFIX=arch- kbuildsycoca6 &")
    hl.exec_cmd("kdeconnectd &")
    hl.exec_cmd("kdeconnect-indicator &")

    hl.exec_cmd("wl-paste --type text --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")

    hl.exec_cmd("ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &")

    hl.exec_cmd("~/.config/hypr/scripts/event-handler.sh &")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- https://www.gnome-look.org/p/1681315: Tokyonight-Dark-Storm-BL-LB.zip
hl.env("GTK_THEME", "Tokyonight-Dark-Storm:dark")
hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    autogenerated = false,

    general = {
        gaps_in          = 0,
        gaps_out         = 0,

        border_size      = 2,

        col              = {
            active_border   = { colors = { "rgba(3d59a1ee)", "rgba(7dcfffee)" }, angle = 45 },
            inactive_border = "rgba(1a1b26ff)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing    = false,

        layout           = "scrolling",

        snap             = {
            enabled = true,
        },
    },

    decoration = {
        rounding         = 4,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.95,

        dim_inactive     = true,
        dim_strength     = 0.2,

        shadow           = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur             = {
            enabled  = true,
            size     = 10,
            passes   = 2,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        allow_session_lock_restore = true,
        mouse_move_enables_dpms = true,
        focus_on_activate = true,

        -- Application not responding dialog
        enable_anr_dialog = true,
        anr_missed_pings = 5,
    },

    binds = {
        workspace_back_and_forth = true,
        hide_special_on_workspace_change = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "default", style = "popin 90%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "default", style = "popin 90%" })
hl.animation({ leaf = "border", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "default", style = "slidefadevert 10%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "default", style = "slidefadevert 20%" })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true,
        force_split = 2, -- Always split to the right/bottom
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 0.5,
        focus_fit_method = 1,
        follow_focus = true,
        follow_min_visible = 0.4,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
        direction = "right",
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout                   = "us",
        kb_variant                  = "",
        kb_model                    = "",

        -- This does:
        --   right alt (or alt gr) => compose key
        --   numpad always activated (no need for numlock)
        --   caps lock => ctrl
        kb_options                  = "compose:ralt, numpad:mac, ctrl:nocaps",
        kb_rules                    = "",
        repeat_delay                = 400,

        follow_mouse                = 2,
        float_switch_override_focus = 0,

        sensitivity                 = 0, -- -1.0 - 1.0, 0 means no modification.
        accel_profile               = "flat",

        touchpad                    = {
            natural_scroll = true,
            scroll_factor = 0.5,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "vertical",
    action = "workspace"
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "scroll_move"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    -- Any receiver mouse technically, but in this case for the M575 Trackball
    name = "logitech-usb-receiver-mouse",
    sensitivity = -0.2,
    accel_profile = "adaptive",

    scroll_method = "on_button_down",
    scroll_button = 274,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Close window
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("~/.config/hypr/scripts/kill-or-minimize.sh"))

-- Exit Hyprland
hl.bind(mainMod .. " + Delete", hl.dsp.exit())

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT_L + T", hl.dsp.exec_cmd(terminalAlt))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
-- hl.bind(mainMod .. " + SHIFT_L + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd(windowSwitcher))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT_L + B", hl.dsp.exec_cmd(browser2))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(passwordManager))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(messagingPlatform))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(messagingPlatformAlt))

-- On laptop lid
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

-- Lock such that, even when the lockscreen dies, it can be relaunched
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("killall hyprlock; hyprlock"), { locked = true })
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("killall hyprlock; hyprlock"), { locked = true })

-- Move focus with mainMod + HL
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))

-- TODO: buggy
-- Cycle windows, useful when there is a mix of floating and tiled, or when multimonitor wants to focus a neighboring workspace instead of the next window
-- hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.cycle_next({ prev = true }))
-- hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.alter_zorder({ mode = "top" }))
-- hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.cycle_next())
-- hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.alter_zorder({ mode = "top" }))

-- Move to previous/next workspace with mainMod + JK
hl.bind(mainMod .. " + J", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ workspace = "m-1" }))

-- Focus on last focused window
hl.bind(mainMod .. " + ALT + TAB", hl.dsp.focus({ last = true }))
hl.bind(mainMod .. " + ALT + TAB", hl.dsp.window.alter_zorder({ mode = "top" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Move window
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ workspace = "+1" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.layout("swapcol l"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.layout("swapcol r"))

-- Resize column to one of the predefined values
hl.bind(mainMod .. " + Left", hl.dsp.layout("colresize -conf"))
hl.bind(mainMod .. " + Right", hl.dsp.layout("colresize +conf"))

-- Special workspace: scratchpad
hl.bind(mainMod .. " + C", hl.dsp.workspace.toggle_special("scratch"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.move({ workspace = "special:scratch" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Multimedia keys for volume control
hl.bind("XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(
        "bash -c \"[[ $(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | cut -d / -f 2 | cut -d % -f 1) -lt 100 ]] && pactl set-sink-volume @DEFAULT_SINK@ +5%\"; paplay /usr/share/sounds/ocean/stereo/audio-volume-change.oga; notify-send -a \"Volume\" -t 1500 \"Volume\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | cut -d / -f 2)\" -p -r $(cat /tmp/volume-notif-id || echo -n 0) > /tmp/volume-notif-id"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
    hl.dsp.exec_cmd(
        "pactl set-sink-volume @DEFAULT_SINK@ -5%; paplay /usr/share/sounds/ocean/stereo/audio-volume-change.oga; notify-send -a \"Volume\" -t 1500 \"Volume\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | cut -d / -f 2)\" -p -r $(cat /tmp/volume-notif-id || echo -n 0) > /tmp/volume-notif-id"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"),
    { locked = true, repeating = true })

-- Screen brightness (laptop)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Media control
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Clipboard manager
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(clipboardManager))

-- Zen mode
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("killall waybar -SIGUSR1"))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-zen.sh"))

-- Multi-monitor
hl.bind(mainMod .. " + I", hl.dsp.workspace.move({ monitor = "+1" }))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.workspace.swap_monitors({ monitor1 = "eDP-1", monitor2 =  "HDMI-A-1" }))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.workspace.swap_monitors({ monitor1 = "DP-1", monitor2 = "HDMI-A-1" }))

-- Calculator
hl.bind(mainMod .. " + Comma", hl.dsp.exec_cmd("qalculate-qt"))

-- Screenshot with selection
hl.bind(mainMod .. " + S",
    hl.dsp.exec_cmd(
        "killall slurp || grim -g \"$(slurp)\" \"$HOME/Pictures/Snip_$(date +%Y%m%d_%Hh%Mm%Ss).png\" && wl-copy < \"$HOME/Pictures/Snip_$(date +%Y%m%d_%Hh%Mm%Ss).png\" && notify-send -t 3000 \"Screenshot taken and copied to clipboard\" -i \"$HOME/Pictures/$(ls ~/Pictures | grep Snip | sort | tail -n 1)\""))
-- More variants in Leader submap


-- Submaps!
-- Mimic Neovim's leader or Tmux's prefix key scheme to create keybind sequences

-- Leader key will be SUPER (pressed and released by itself)
hl.bind(mainMod .. " + SUPER_L", hl.dsp.submap("Leader"), { release = true, ignore_mods = true })

hl.define_submap("Leader", function()
    -- Launch the application menu
    hl.bind("Space", hl.dsp.exec_cmd(menu))

    -- Control menus
    hl.bind("Q", hl.dsp.exec_cmd(powerMenu))
    hl.bind("B", hl.dsp.exec_cmd(bluetoothMenu))
    hl.bind("W", hl.dsp.exec_cmd(wifiMenu))
    hl.bind("N", hl.dsp.exec_cmd("swaync-client -t -sw"))

    -- Lock
    hl.bind("ALT + L", hl.dsp.exec_cmd("killall hyprlock; hyprlock"))

    -- Move to the next *numerical* workspace
    hl.bind(mainMod .. " + J", hl.dsp.focus({ workspace = "r+1" }), { repeating = true })
    hl.bind(mainMod .. " + K", hl.dsp.focus({ workspace = "r-1" }))

    -- Center floating window
    hl.bind("C", hl.dsp.window.center())

    -- Screenshots
    -- screen
    hl.bind("S",
        hl.dsp.exec_cmd(
            "grim \"$HOME/Pictures/Screenshot_$(date +%Y%m%d_%Hh%Mm%Ss).png\" && notify-send -t 3000 \"Screenshot taken\" -i \"$HOME/Pictures/$(ls ~/Pictures | grep Screenshot | sort | tail -n 1)\""))
    hl.bind("SHIFT + S",
        hl.dsp.exec_cmd(
            "grim -g \"$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1) $(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)\" \"$HOME/Pictures/Windowshot_$(date +%Y%m%d_%Hh%Mm%Ss).png\" && notify-send -t 3000 \"Screenshot of active window taken\" -i \"$HOME/Pictures/$(ls ~/Pictures | grep Windowshot | sort | tail -n 1)\""))

    -- Restart waybar
    hl.bind("ALT + W", hl.dsp.exec_cmd("killall waybar; ~/.config/hypr/scripts/waybar-dynamic-config.sh && waybar &!"))

    -- Reload all eww widgets
    hl.bind("ALT + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/eww-open-all.sh"))

    -- The flags make it possible to just tap SUPER again to reset the submap
    hl.bind("catchall", hl.dsp.submap("reset"), { release = true, ignore_mods = true })
end)

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Example window rules that are useful

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name           = "suppress-maximize-events",
    match          = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name     = "fix-xwayland-drags",
    match    = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Scratchpad
hl.workspace_rule({
    workspace = "special:scratch",
    on_created_empty = "[float; size (monitor_w*0.5) (monitor_h*0.6); center] " .. terminal,
})

-- Make calculator float
hl.window_rule({
    name = "calculator-float",
    match = {
        class = "^io.github.Qalculate.qalculate-qt$",
    },
    float = true,
    size = { "(monitor_w*0.3)", "(monitor_h*0.8)" },
    move = { "(monitor_w*0.6)", "(monitor_h*0.05)" },
})
