-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

hl.config({
    autogenerated = false
})

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Default
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---

require("modules.programs")
require("modules.autostart")
require("modules.environment")

-- Set configs specific to a certain machine, like monitor configs, that differ from the default.
--
-- Create an empty "local.lua" file if no specific configs are needed.
require("modules.local")

-----------------------
----- PERMISSIONS -----
-----------------------

-- TODO

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

---

require("modules.looks")
require("modules.behavior")
require("modules.layout")
require("modules.input")
require("modules.keybinds")
require("modules.rules")
