[window]
# decorations = "None"
# startup_mode = "Fullscreen"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 10

[terminal]
osc52 = "OnlyCopy"

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Backspace", mods = "Control", chars = "\u0017" },
    { key = "NumpadEnter", chars = "\r" },
    { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" }
]

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#16161e'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#f76f00'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

